#!/usr/bin/env python3
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
"""
Ports iOS `GeneratedSpeciesFrames.swift` into Kotlin
`android/buddy-ui/src/main/kotlin/com/openvibble/ui/species/GeneratedSpecies.kt`.

The iOS file is itself auto-generated by `scripts/gen_species_frames.py` from
species JSON, so we mirror that contract instead of editing the Kotlin file
by hand.

Usage:
    python3 android/scripts/gen_species_kt.py
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SWIFT_SRC = ROOT / "Packages" / "OpenVibbleKit" / "Sources" / "BuddyUI" / "ASCIISpecies" / "GeneratedSpeciesFrames.swift"
KT_DST = ROOT / "android" / "buddy-ui" / "src" / "main" / "kotlin" / "com" / "openvibble" / "ui" / "species" / "GeneratedSpecies.kt"

SWIFT_STATE_TO_KT: dict[str, str] = {
    ".sleep": "PersonaState.SLEEP",
    ".idle": "PersonaState.IDLE",
    ".busy": "PersonaState.BUSY",
    ".attention": "PersonaState.ATTENTION",
    ".celebrate": "PersonaState.CELEBRATE",
    ".dizzy": "PersonaState.DIZZY",
    ".heart": "PersonaState.HEART",
}

SPECIES_ENTRY_RE = re.compile(
    r"private static let (?P<name>\w+): \[PersonaState: SpeciesStateData\] = \[\n(?P<body>.*?)\n {4}\]\n",
    re.DOTALL,
)


def parse_swift_string(src: str, idx: int) -> tuple[str, int]:
    """Parse a Swift string literal starting at `idx` (src[idx] == '"').

    Returns the raw contents (with original escapes preserved) and the index
    just after the closing quote. Handles escaped quotes/backslashes so the
    frame text — which contains characters like `"` inside quotes — passes
    through unchanged. Swift and Kotlin share the same escape sequences we
    care about (\\, \", \n), so we can re-emit the original substring verbatim.
    """
    assert src[idx] == '"', f"expected '\"' at {idx}, got {src[idx]!r}"
    start = idx
    idx += 1
    while idx < len(src):
        ch = src[idx]
        if ch == "\\":
            idx += 2
            continue
        if ch == '"':
            return src[start + 1 : idx], idx + 1
        idx += 1
    raise ValueError("unterminated string literal")


def parse_string_array(src: str, idx: int) -> tuple[list[str], int]:
    """Parse `[ "line1", "line2", ... ]` and return list of raw literals."""
    assert src[idx] == "[", f"expected '[' at {idx}"
    idx += 1
    out: list[str] = []
    while True:
        while idx < len(src) and src[idx] in " \t\n":
            idx += 1
        if src[idx] == "]":
            return out, idx + 1
        if src[idx] == ",":
            idx += 1
            continue
        literal, idx = parse_swift_string(src, idx)
        out.append(literal)


def parse_frames(src: str, idx: int) -> tuple[list[list[str]], int]:
    """Parse `[ [...], [...] ]` into list of frames."""
    assert src[idx] == "[", f"expected '[' at {idx}"
    idx += 1
    out: list[list[str]] = []
    while True:
        while idx < len(src) and src[idx] in " \t\n":
            idx += 1
        if src[idx] == "]":
            return out, idx + 1
        if src[idx] == ",":
            idx += 1
            continue
        frame, idx = parse_string_array(src, idx)
        out.append(frame)


def parse_int_array(src: str, idx: int) -> tuple[list[int], int]:
    assert src[idx] == "[", f"expected '[' at {idx}"
    idx += 1
    buf = ""
    out: list[int] = []
    while idx < len(src):
        ch = src[idx]
        if ch == "]":
            if buf.strip():
                out.append(int(buf.strip()))
            return out, idx + 1
        if ch == ",":
            if buf.strip():
                out.append(int(buf.strip()))
            buf = ""
            idx += 1
            continue
        buf += ch
        idx += 1
    raise ValueError("unterminated int array")


def parse_species_states(body: str) -> list[tuple[str, list[list[str]], list[int], str]]:
    """
    Body form (one line per state):
        .sleep: SpeciesStateData(frames: [...], seq: [...], colorRGB565: 0xAAAA),
        ...
    Returns list of (swift_state_key, frames, seq, color_literal).
    """
    out: list[tuple[str, list[list[str]], list[int], str]] = []
    lines = [ln.strip() for ln in body.strip().splitlines() if ln.strip()]
    for line in lines:
        m = re.match(
            r"(?P<state>\.\w+): SpeciesStateData\(frames: (?P<rest>.*)\),?$",
            line,
        )
        if not m:
            raise ValueError(f"unexpected state line: {line!r}")
        state = m.group("state")
        rest = m.group("rest")
        # rest is: [frames...], seq: [ints...], colorRGB565: 0xXXXX)
        frames, cursor = parse_frames(rest, 0)
        seq_prefix = ", seq: "
        assert rest[cursor : cursor + len(seq_prefix)] == seq_prefix, rest[cursor : cursor + 20]
        cursor += len(seq_prefix)
        seq, cursor = parse_int_array(rest, cursor)
        color_prefix = ", colorRGB565: "
        assert rest[cursor : cursor + len(color_prefix)] == color_prefix, rest[cursor : cursor + 20]
        cursor += len(color_prefix)
        end = rest.find(")", cursor)
        if end == -1:
            end = len(rest)
        color = rest[cursor:end].strip()
        out.append((state, frames, seq, color))
    return out


def kt_string(raw: str) -> str:
    """Emit a Kotlin string literal from a raw Swift-compatible literal body."""
    # Swift and Kotlin share `\"`, `\\`, `\n` escape semantics; other chars in
    # the auto-generated frames are printable ASCII, so re-wrapping in quotes
    # is safe.
    return '"' + raw + '"'


def emit_kotlin(species: list[tuple[str, list[tuple[str, list[list[str]], list[int], str]]]]) -> str:
    lines: list[str] = []
    lines.append(
        "// This Source Code Form is subject to the terms of the Mozilla Public\n"
        "// License, v. 2.0. If a copy of the MPL was not distributed with this\n"
        "// file, You can obtain one at https://mozilla.org/MPL/2.0/.\n"
        "\n"
        "// AUTO-GENERATED by android/scripts/gen_species_kt.py from\n"
        "// Packages/OpenVibbleKit/Sources/BuddyUI/ASCIISpecies/GeneratedSpeciesFrames.swift.\n"
        "// Do not edit by hand — run the script after regenerating the iOS file.\n"
        "package com.openvibble.ui.species\n"
        "\n"
        "import com.openvibble.persona.PersonaState\n"
        "\n"
        "object GeneratedSpecies {\n"
    )

    for name, states in species:
        lines.append(f"    private val {name}: Map<PersonaState, SpeciesStateData> = mapOf(\n")
        for swift_state, frames, seq, color in states:
            kt_state = SWIFT_STATE_TO_KT[swift_state]
            lines.append(f"        {kt_state} to SpeciesStateData(\n")
            lines.append("            frames = listOf(\n")
            for frame in frames:
                inner = ", ".join(kt_string(line) for line in frame)
                lines.append(f"                listOf({inner}),\n")
            lines.append("            ),\n")
            seq_inner = ", ".join(str(v) for v in seq)
            lines.append(f"            seq = listOf({seq_inner}),\n")
            lines.append(f"            colorRGB565 = {color},\n")
            lines.append("        ),\n")
        lines.append("    )\n\n")
    lines.append("    val all: Map<String, Map<PersonaState, SpeciesStateData>> = mapOf(\n")
    for name, _ in species:
        lines.append(f'        "{name}" to {name},\n')
    lines.append("    )\n")
    lines.append("}\n")
    return "".join(lines)


def main() -> int:
    text = SWIFT_SRC.read_text(encoding="utf-8")
    entries: list[tuple[str, list]] = []
    for m in SPECIES_ENTRY_RE.finditer(text):
        name = m.group("name")
        body = m.group("body")
        states = parse_species_states(body)
        entries.append((name, states))
    if not entries:
        print("no species parsed", file=sys.stderr)
        return 1
    KT_DST.write_text(emit_kotlin(entries), encoding="utf-8")
    print(f"wrote {KT_DST} with {len(entries)} species", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
