#!/usr/bin/env python3
"""Extract ASCII frame tables, SEQ arrays, and bodyColor from
claude-desktop-buddy firmware .cpp files, emitting a Swift source file."""

import re
import sys
from pathlib import Path

STATE_FUNCS = {
    "doSleep": "sleep",
    "doIdle": "idle",
    "doBusy": "busy",
    "doAttention": "attention",
    "doCelebrate": "celebrate",
    "doDizzy": "dizzy",
    "doHeart": "heart",
}

RE_NAMESPACE = re.compile(r"namespace\s+(\w+)\s*\{")
RE_FRAME_TABLE = re.compile(
    r'static\s+const\s+char\s*\*\s*const\s+(\w+)\s*\[\s*5\s*\]\s*=\s*\{((?:[^}"]*(?:"[^"]*")?)*)\};',
    re.DOTALL,
)
RE_P_ARRAY = re.compile(
    r'const\s+char\s*\*\s*const\s*\*\s*P\s*\[\s*\d+\s*\]\s*=\s*\{([^}]+)\};',
    re.DOTALL,
)
RE_SEQ = re.compile(
    r'static\s+const\s+uint8_t\s+SEQ\s*\[\s*\]\s*=\s*\{([^}]+)\};',
    re.DOTALL,
)
RE_PRINT_SPRITE = re.compile(
    r'buddyPrintSprite\s*\(\s*[^,]+,\s*\d+\s*,\s*\d+\s*,\s*0x([0-9A-Fa-f]+)\s*\)',
)


def _extract_strings(block: str) -> list:
    # Extract quoted strings in order (handles escapes by matching content
    # between unescaped quotes, which is sufficient for firmware source).
    out = []
    i = 0
    while i < len(block):
        if block[i] == '"':
            j = i + 1
            buf = []
            while j < len(block) and block[j] != '"':
                if block[j] == '\\' and j + 1 < len(block):
                    buf.append(block[j:j+2])
                    j += 2
                else:
                    buf.append(block[j])
                    j += 1
            # Decode escapes we care about (\\ -> \)
            s = "".join(buf).encode().decode("unicode_escape")
            out.append(s)
            i = j + 1
        else:
            i += 1
    return out


def _split_state_bodies(src: str) -> dict:
    """Return {state_key: body_text} slices between `static void doXxx(` markers."""
    bodies = {}
    markers = []
    for func, key in STATE_FUNCS.items():
        m = re.search(rf'static\s+void\s+{func}\s*\(', src)
        if m:
            markers.append((m.start(), key))
    markers.sort()
    for idx, (start, key) in enumerate(markers):
        end = markers[idx + 1][0] if idx + 1 < len(markers) else len(src)
        bodies[key] = src[start:end]
    return bodies


def parse_species_file(path: Path) -> dict:
    src = path.read_text()
    ns = RE_NAMESPACE.search(src)
    name = ns.group(1) if ns else path.stem
    result = {"name": name, "states": {}}
    for state_key, body in _split_state_bodies(src).items():
        tables = {}
        for m in RE_FRAME_TABLE.finditer(body):
            tbl_name = m.group(1)
            strings = _extract_strings(m.group(2))
            if len(strings) == 5:
                tables[tbl_name] = strings
        p_match = RE_P_ARRAY.search(body)
        if p_match:
            order = [t.strip() for t in p_match.group(1).split(",") if t.strip()]
            frames = [tables[n] for n in order if n in tables]
        else:
            frames = list(tables.values())
        seq_match = RE_SEQ.search(body)
        seq = []
        if seq_match:
            seq = [int(x.strip()) for x in seq_match.group(1).split(",") if x.strip()]
        color_match = RE_PRINT_SPRITE.search(body)
        color = int(color_match.group(1), 16) if color_match else 0xFFFF
        result["states"][state_key] = {
            "frames": frames,
            "seq": seq,
            "color_rgb565": color,
        }
    return result


def emit_swift(species: list, output: Path) -> None:
    lines = [
        "// AUTO-GENERATED by scripts/gen_species_frames.py",
        "// Do not edit by hand. Overlays section is hand-maintained — see OverlaySpec.swift.",
        "import BuddyPersona",
        "",
        "public enum GeneratedSpecies {",
        "    public static let all: [String: [PersonaState: SpeciesStateData]] = [",
    ]
    for sp in species:
        lines.append(f'        "{sp["name"]}": [')
        for state, data in sp["states"].items():
            frames_literal = ", ".join(
                "[" + ", ".join(f'"{_esc(s)}"' for s in frame) + "]"
                for frame in data["frames"]
            )
            seq_literal = ", ".join(str(i) for i in data["seq"])
            lines.append(
                f'            .{state}: SpeciesStateData('
                f'frames: [{frames_literal}], seq: [{seq_literal}], '
                f'colorRGB565: 0x{data["color_rgb565"]:04X}),'
            )
        lines.append("        ],")
    lines.append("    ]")
    lines.append("}")
    output.write_text("\n".join(lines) + "\n")


def _esc(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: gen_species_frames.py <buddies_dir> <output.swift>", file=sys.stderr)
        return 2
    buddies_dir = Path(sys.argv[1])
    output = Path(sys.argv[2])
    species = [parse_species_file(p) for p in sorted(buddies_dir.glob("*.cpp"))]
    emit_swift(species, output)
    print(f"wrote {len(species)} species to {output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
